/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as EventEventSlugRouteImport } from './routes/event.$eventSlug'
import { Route as DemoAdminRouteImport } from './routes/demo.admin'
import { Route as EventEventSlugIndexRouteImport } from './routes/event.$eventSlug.index'
import { Route as EventEventSlugAdminRouteImport } from './routes/event.$eventSlug.admin'
import { Route as DemoTeamTeamIdRouteImport } from './routes/demo.team.$teamId'
import { Route as EventEventSlugTeamTeamIdRouteImport } from './routes/event.$eventSlug.team.$teamId'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventSlugRoute = EventEventSlugRouteImport.update({
  id: '/event/$eventSlug',
  path: '/event/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAdminRoute = DemoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DemoRoute,
} as any)
const EventEventSlugIndexRoute = EventEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventEventSlugRoute,
} as any)
const EventEventSlugAdminRoute = EventEventSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => EventEventSlugRoute,
} as any)
const DemoTeamTeamIdRoute = DemoTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => DemoRoute,
} as any)
const EventEventSlugTeamTeamIdRoute =
  EventEventSlugTeamTeamIdRouteImport.update({
    id: '/team/$teamId',
    path: '/team/$teamId',
    getParentRoute: () => EventEventSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRouteWithChildren
  '/super-admin': typeof SuperAdminRoute
  '/demo/admin': typeof DemoAdminRoute
  '/event/$eventSlug': typeof EventEventSlugRouteWithChildren
  '/team/$teamId': typeof TeamTeamIdRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/team/$teamId': typeof DemoTeamTeamIdRoute
  '/event/$eventSlug/admin': typeof EventEventSlugAdminRoute
  '/event/$eventSlug/': typeof EventEventSlugIndexRoute
  '/event/$eventSlug/team/$teamId': typeof EventEventSlugTeamTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/super-admin': typeof SuperAdminRoute
  '/demo/admin': typeof DemoAdminRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/demo': typeof DemoIndexRoute
  '/demo/team/$teamId': typeof DemoTeamTeamIdRoute
  '/event/$eventSlug/admin': typeof EventEventSlugAdminRoute
  '/event/$eventSlug': typeof EventEventSlugIndexRoute
  '/event/$eventSlug/team/$teamId': typeof EventEventSlugTeamTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRouteWithChildren
  '/super-admin': typeof SuperAdminRoute
  '/demo/admin': typeof DemoAdminRoute
  '/event/$eventSlug': typeof EventEventSlugRouteWithChildren
  '/team/$teamId': typeof TeamTeamIdRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/team/$teamId': typeof DemoTeamTeamIdRoute
  '/event/$eventSlug/admin': typeof EventEventSlugAdminRoute
  '/event/$eventSlug/': typeof EventEventSlugIndexRoute
  '/event/$eventSlug/team/$teamId': typeof EventEventSlugTeamTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/demo'
    | '/super-admin'
    | '/demo/admin'
    | '/event/$eventSlug'
    | '/team/$teamId'
    | '/demo/'
    | '/demo/team/$teamId'
    | '/event/$eventSlug/admin'
    | '/event/$eventSlug/'
    | '/event/$eventSlug/team/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/super-admin'
    | '/demo/admin'
    | '/team/$teamId'
    | '/demo'
    | '/demo/team/$teamId'
    | '/event/$eventSlug/admin'
    | '/event/$eventSlug'
    | '/event/$eventSlug/team/$teamId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/demo'
    | '/super-admin'
    | '/demo/admin'
    | '/event/$eventSlug'
    | '/team/$teamId'
    | '/demo/'
    | '/demo/team/$teamId'
    | '/event/$eventSlug/admin'
    | '/event/$eventSlug/'
    | '/event/$eventSlug/team/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DemoRoute: typeof DemoRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRoute
  EventEventSlugRoute: typeof EventEventSlugRouteWithChildren
  TeamTeamIdRoute: typeof TeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventSlug': {
      id: '/event/$eventSlug'
      path: '/event/$eventSlug'
      fullPath: '/event/$eventSlug'
      preLoaderRoute: typeof EventEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/admin': {
      id: '/demo/admin'
      path: '/admin'
      fullPath: '/demo/admin'
      preLoaderRoute: typeof DemoAdminRouteImport
      parentRoute: typeof DemoRoute
    }
    '/event/$eventSlug/': {
      id: '/event/$eventSlug/'
      path: '/'
      fullPath: '/event/$eventSlug/'
      preLoaderRoute: typeof EventEventSlugIndexRouteImport
      parentRoute: typeof EventEventSlugRoute
    }
    '/event/$eventSlug/admin': {
      id: '/event/$eventSlug/admin'
      path: '/admin'
      fullPath: '/event/$eventSlug/admin'
      preLoaderRoute: typeof EventEventSlugAdminRouteImport
      parentRoute: typeof EventEventSlugRoute
    }
    '/demo/team/$teamId': {
      id: '/demo/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/demo/team/$teamId'
      preLoaderRoute: typeof DemoTeamTeamIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/event/$eventSlug/team/$teamId': {
      id: '/event/$eventSlug/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/event/$eventSlug/team/$teamId'
      preLoaderRoute: typeof EventEventSlugTeamTeamIdRouteImport
      parentRoute: typeof EventEventSlugRoute
    }
  }
}

interface DemoRouteChildren {
  DemoAdminRoute: typeof DemoAdminRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoTeamTeamIdRoute: typeof DemoTeamTeamIdRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAdminRoute: DemoAdminRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoTeamTeamIdRoute: DemoTeamTeamIdRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface EventEventSlugRouteChildren {
  EventEventSlugAdminRoute: typeof EventEventSlugAdminRoute
  EventEventSlugIndexRoute: typeof EventEventSlugIndexRoute
  EventEventSlugTeamTeamIdRoute: typeof EventEventSlugTeamTeamIdRoute
}

const EventEventSlugRouteChildren: EventEventSlugRouteChildren = {
  EventEventSlugAdminRoute: EventEventSlugAdminRoute,
  EventEventSlugIndexRoute: EventEventSlugIndexRoute,
  EventEventSlugTeamTeamIdRoute: EventEventSlugTeamTeamIdRoute,
}

const EventEventSlugRouteWithChildren = EventEventSlugRoute._addFileChildren(
  EventEventSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DemoRoute: DemoRouteWithChildren,
  SuperAdminRoute: SuperAdminRoute,
  EventEventSlugRoute: EventEventSlugRouteWithChildren,
  TeamTeamIdRoute: TeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
